### ISSUE TITLE
Eigen throws std::bad_alloc at construction

### ISSUE THREAD

**Issue by alexge233** [OpenANN/OpenANN#173]
I'm trying to initialize a deep network, with 406 input nodes, 2 output nodes, 5 hidden layers, each with 10 hidden nodes:

```
36     OpenANN::makeMLNN(net_,                                                                                                             
37                       OpenANN::RECTIFIER,                                                                                               
38                       OpenANN::SOFTMAX,                                                                                                 
39                       406,                                                                                                     
40                       2,                                                                                                                
41                       5,                                                                                                                
42                       10); 
```

I keep getting:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Running with gdb produces:

```
#0  0x00007ffff58dc107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff58dd4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff61c7b3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff61c5bb6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff61c5c01 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff61c5e19 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000006527c4 in Eigen::internal::throw_std_bad_alloc () at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:88
#7  0x00007ffff64a7523 in OpenANN::FullyConnected::FullyConnected(OpenANN::OutputInfo, int, bool, OpenANN::ActivationFunction, double, OpenANN::Regularization) () from /usr/local/lib/libopenann.so
#8  0x00007ffff64d06e6 in OpenANN::Net::fullyConnectedLayer(int, OpenANN::ActivationFunction, double, bool) () from /usr/local/lib/libopenann.so
#9  0x00007ffff64ec7cc in OpenANN::makeMLNN(OpenANN::Net&, OpenANN::ActivationFunction, OpenANN::ActivationFunction, int, int, int, ...) () 
from /usr/local/lib/libopenann.so
#10 0x0000000000651737 in concept_relation_classifier::train (this=0x4f09950, mem=std::shared_ptr (count 2, weak 0) 0x4f08c40) at /home/alex
/Projects/Icarus/branches/0.0.8/NeuralNets/concept_relation_classifier/concept_relation_classifier.cpp:42
```

Messing about with smaller networks seems to fix the issue: 2 hidden layers are ok, 3 hidden, 4 hidden or 5 hidden layers throws the above exception.

During allocation, I can see the memory usage of the application increasing up to 1.7Gb, which should not cause issues as the system has 12Gb available.

Am I doing something wrong?
How do I go about creating a Deep Neural Network?

**Comment by alexge233** [comment]
Nevermind, I realized I was only setting one layer's nodes, sorry.

**Comment by AlexanderFabisch** [comment]
Unfortunately it is not straightforward to give a meaningful error message in this case.
